# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/sources_1/new/tempReg.v
  F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/sources_1/new/SignZeroExtend.v
  F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/sources_1/new/RegisterFile.v
  F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/sources_1/new/pcAdd.v
  F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/sources_1/new/PC.v
  F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/sources_1/new/IR.v
  F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/sources_1/new/InstructionCut.v
  F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/sources_1/new/InsMEM.v
  F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/sources_1/new/DataMEM.v
  F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/sources_1/new/ControlUnit.v
  F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/sources_1/new/ALU.v
  F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/sources_1/new/MultiCycleCPU.v
  F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/sources_1/new/Debounce.v
  F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/sources_1/new/showCPU.v
}
read_xdc F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/constrs_1/new/cpu.xdc
set_property used_in_implementation false [get_files F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.srcs/constrs_1/new/cpu.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Vivado/CPUBasys_Mutli/CPUBasys_Mutli.cache/wt [current_project]
set_property parent.project_dir F:/Vivado/CPUBasys_Mutli [current_project]
catch { write_hwdef -file showCPU.hwdef }
synth_design -top showCPU -part xc7a35tcpg236-1
write_checkpoint showCPU.dcp
report_utilization -file showCPU_utilization_synth.rpt -pb showCPU_utilization_synth.pb
